/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nfTokenSol from "./NFToken.sol";
export type { nfTokenSol };
import type * as nfTuneSol from "./NFTune.sol";
export type { nfTuneSol };
export type { AccessManager } from "./AccessManager";
