/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721BurnableUpgradeable__factory } from "./ERC721BurnableUpgradeable__factory";
export { ERC721URIStorageUpgradeable__factory } from "./ERC721URIStorageUpgradeable__factory";
