/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyToken__factory } from "./MyToken__factory";
export { NFToken__factory } from "./NFToken__factory";
