/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessManaged } from "./AccessManaged";
export type { IAccessManaged } from "./IAccessManaged";
export type { IAccessManager } from "./IAccessManager";
export type { IAuthority } from "./IAuthority";
