/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721BurnableUpgradeable } from "./ERC721BurnableUpgradeable";
export type { ERC721URIStorageUpgradeable } from "./ERC721URIStorageUpgradeable";
